### Create a new link
POST http://localhost:3000/create
Content-Type: application/json
x-api-key: password

{
  "targetUrl": "https://www.p3s.dev"
}

### Get a link
GET http://localhost:3000/MjQxMTI4NzE3OA

### Update a link
PATCH http://localhost:3000/MjQxMTI4NzE3OA
Content-Type: application/json
x-api-key: password

{
  "targetUrl": "https://www.google.com"
}

### Get link statistics
GET http://localhost:3000/MjQxMTI4NzE3OA/stats
x-api-key: password